create database payroll_service;
show databases;
use payroll_service;
create table payroll_service (id int NOT NUll auto_increment, name varchar(200) NOT NULL, salary double NOT NUll, start date NOT NULL, primary key (id));
rename table payroll_service to employee_service;
desc employee_service;
insert into employee_service value (1,'Nadeem Shaikh', 500000.0, '2018-12-01');
insert into employee_service value (2, 'Sameer Shaikh', 600000.0, '2019-11-02');
insert into employee_service value (3, 'Ali Shaikh', 700000.0, '2020-10-03');
select * from employee_service;
insert into employee_service(name,salary,start) values ('Natasha',800000.0,'2021-09-04');
select * from employee_service;
select salary from employee_service where name='Nadeem Shaikh';
select salary from employee_service where start between cast('2019-11-02' as date) and date(now());
select * from employee_service where start between cast('2019-11-02' as date) and date(now());
select * from employee_service where start between cast('2021-09-04' as date) and date(now());
alter table employee_service add gender char(1) after name;
desc employee_service;
update employee_service set gender ='M' where name = 'Nadeem Shaikh' or  name = 'Sameer Shaikh' or  name = 'Ali Shaikh';
update employee_service set gender ='F' where name = 'Natasha';
select* from employee_service;
select sum(salary) from employee_service where gender ='M' group by gender;
select avg(salary) from employee_service where gender ='M' group by gender;
select gender,count(salary) from employee_service group by gender;
select name, gender, min(salary) from employee_service group by gender;
select name, gender, max(salary) from employee_service group by gender;
alter table employee_service add phone_num varchar(15) after name;
alter table employee_service add address varchar(100) after phone_num;
alter table employee_service add department varchar(100) after address;
desc employee_service;
select* from employee_service;
alter table employee_service rename column salary to basic_pay;
alter table employee_service add deduction double NOT NULL after basic_pay; 
alter table employee_service add taxable_pay double NOT NULL after deduction; 
alter table employee_service add tax double NOT NULL after taxable_pay;
alter table employee_service add net_pay double NOT NULL after tax;
desc employee_service;
select* from employee_service;
insert into employee_service (name,department,gender,basic_pay,deduction,taxable_pay,tax,net_pay,start) values('Nadeem Shaikh','Marketing','M','4000000','1000000','2000000','60000','800000','2018-01-03');
select* from employee_service;
select* from employee_service where name ='Nadeem Shaikh';
create table Department(department varchar(150)NOT NULL, primary key(department));
insert into Department(department) values ('sale'),('Marketing');  
select * from department;
create table Employee (id int, phone_num BIGINT(15),address varchar(25),gender char(1),primary key(id));
select * from employee;
insert into Employee(id, phone_num, address,gender) values(1,7875692054,'Pune','M'),(2,8208022703,'GOA','M');
select* from Employee;
create table Emp_Department (empID int, Depart varchar(250) NOT NULL, FOREIGN KEY (empID) REFERENCES Employee (id),FOREIGN KEY (Depart) REFERENCES Department (department), PRIMARY KEY (empID, Depart));
desc Emp_Department;
insert into Emp_Department (empID, Depart) VALUES (1, 'Marketing');
select* from Emp_Department;
select * from Emp_Department where empId = 1;
insert into Emp_Department (empID, Depart) VALUES (2, 'Sales');